#!/bin/sh
#https://laraveldaily.com/post/laravel-pint-pre-commit-hooks-github-actions
phpFiles=$(git diff --cached --name-only --diff-filter=ACM -- '*.php');
resourceFiles=$(git diff --cached --name-only --diff-filter=ACM -- resources/);
vendor/bin/rector
vendor/bin/duster fix --dirty
#Sort tailwind classes
rustywind --write resources/
git add $phpFiles
git add $resourceFiles
